import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "npm:@supabase/supabase-js@2"
import nodemailer from "npm:nodemailer@6"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const MAX_PENDING_INVITATIONS = 5

interface RequestBody {
  invitee_email: string
  label: 'family' | 'friend' | null
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const authHeader = req.headers.get('Authorization')
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Missing authorization header' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 401,
    })
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!
  const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!
  const appUrl = Deno.env.get('APP_URL') ?? 'https://shopping-recipies-events.vercel.app'
  const smtpPassword = Deno.env.get('GMAIL_SMTP_PASSWORD')

  // Use the caller's JWT for all DB operations — RLS is scoped to auth.uid() so no service role needed
  const supabase = createClient(supabaseUrl, supabaseAnonKey, {
    global: { headers: { Authorization: authHeader } },
  })

  const { data: { user }, error: userError } = await supabase.auth.getUser()
  if (userError || !user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 401,
    })
  }

  try {
    const { invitee_email, label } = (await req.json()) as RequestBody

    if (!invitee_email) {
      return new Response(JSON.stringify({ error: 'invitee_email is required' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      })
    }

    const normalizedEmail = invitee_email.trim().toLowerCase()

    // Guard: cannot invite yourself
    if (user.email?.toLowerCase() === normalizedEmail) {
      return new Response(JSON.stringify({ error: 'self_invite' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      })
    }

    const now = new Date().toISOString()

    // Check for existing active (pending, non-expired) invitation to this email from this inviter
    const { data: existing } = await supabase
      .from('contact_invitations')
      .select('token')
      .eq('inviter_id', user.id)
      .eq('invitee_email', normalizedEmail)
      .eq('status', 'pending')
      .gt('expires_at', now)
      .maybeSingle()

    if (existing) {
      return new Response(JSON.stringify({ ok: true, token: existing.token }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Guard: max 5 pending invitations per inviter (anti-spam)
    const { count } = await supabase
      .from('contact_invitations')
      .select('id', { count: 'exact', head: true })
      .eq('inviter_id', user.id)
      .eq('status', 'pending')
      .gt('expires_at', now)

    if ((count ?? 0) >= MAX_PENDING_INVITATIONS) {
      return new Response(JSON.stringify({ error: 'spam_limit' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 429,
      })
    }

    // Insert invitation row (token generated by Postgres default)
    const { data: invitation, error: insertError } = await supabase
      .from('contact_invitations')
      .insert({ inviter_id: user.id, invitee_email: normalizedEmail, label: label ?? null })
      .select('token')
      .single()

    if (insertError || !invitation) {
      console.error('Insert error:', insertError)
      return new Response(JSON.stringify({ error: 'Failed to create invitation' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      })
    }

    // Resolve inviter display name
    const { data: profile } = await supabase
      .from('profiles')
      .select('display_name')
      .eq('user_id', user.id)
      .single()

    const inviterName = profile?.display_name ?? user.email ?? 'Someone'
    const labelText = label === 'family' ? 'Family' : label === 'friend' ? 'Friend' : 'Contact'
    const acceptUrl = `${appUrl}/invite/accept?token=${invitation.token}`

    if (smtpPassword) {
      try {
        const transporter = nodemailer.createTransport({
          host: 'smtp.gmail.com',
          port: 587,
          secure: false,
          auth: {
            user: 'shopcookhost@gmail.com',
            pass: smtpPassword,
          },
        })

        await transporter.sendMail({
          from: '"Shop Cook Host" <shopcookhost@gmail.com>',
          to: normalizedEmail,
          subject: `${inviterName} invited you to connect on Shop Cook Host`,
          html: `
            <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
              <h2 style="color: #6366f1;">Shop Cook Host</h2>
              <p>${inviterName} wants to add you as a <strong>${labelText}</strong> on Shop Cook Host.</p>
              <p style="margin: 32px 0;">
                <a href="${acceptUrl}"
                   style="background:#6366f1;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:bold;">
                  Accept Invitation
                </a>
              </p>
              <p style="color:#6b7280;font-size:14px;">This invitation expires in 24 hours.</p>
              <p style="color:#6b7280;font-size:14px;">If you didn't expect this, you can safely ignore it.</p>
            </div>
          `,
        })
      } catch (emailErr) {
        // Log but don't fail — the invitation row exists and the link is still valid
        console.error('Email send failed:', (emailErr as Error).message)
      }
    } else {
      console.warn('GMAIL_SMTP_PASSWORD not set — skipping email send')
    }

    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('Caught error:', (err as Error).message)
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    })
  }
})
